### ISSUE TITLE
Limitación de responsabilidad.

### ISSUE THREAD

**Issue by torbellina** [Ingobernable/kaos155#17]
Como obtenemos nuestros datos de fuentes accesibles al público, para no tener problemas, quizás deberíamos avisarlo de la misma manera que lo hace el Libreborme en un párrafo dentro de su Aviso Legal:

Limitación de responsabilidad

La información que muestra LibreBORME se ha obtenido de fuentes accesibles al público y cuyos datos se presumen correctos. Debido a que la recopilación de los datos es un proceso informático automatizado y a que la enorme cantidad de datos hace imposible su completa verificación, LibreBORME no asume responsabilidad alguna por errores, inexactitudes u omisiones de la información facilitada.

El USUARIO no podrá exigir responsabilidad alguna por los daños y perjuicios derivados de errores y/o incorrección y/o inexactitud en la información suministrada y acepta que la información suministrada en la PAGINA WEB se ofrece con carácter orientativo.

El USUARIO es el único responsable de las infracciones en las que pueda incurrir o de los perjuicios que pueda causar o causarse por la utilización de la PAGINA WEB, quedando LibreBORME, exonerado de cualquier clase de responsabilidad que se pudiera derivar por las acciones del USUARIO.

**Comment by ghost** [comment]
Torbellina la propia Licencia contempla esto. Se distribuye kaos155 sin garantias. Se espera que sea de utilidad pero no se garantiza que lo sea ni nos hacemos responsables del uso que le puedas dar.

Esto está en la GPL como no garantia y limitación de responsabilidad

**Comment by ghost** [comment]
15. Disclaimer of Warranty.

  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY
APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT
HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY
OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM
IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF
ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

  16. Limitation of Liability.

  IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS
THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY
GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE
USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF
DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD
PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS),
EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGES.

**Comment by torbellina** [comment]
oooh he aprendido a cerrar !!! jajajajaja
